### PR TITLE
Fix mouseDown flag not getting reset, which prevents list from closing on blur

### LINKED ISSUE #18: mouseup event not triggered if result option is dragged
If a result option is dragged outside of `<ul id="users-popup"></ul>` the  `this.mouseDown` flag is set to `true` but it never turns back to `false` (unless you click any option from the list), so the popup can not be closed on input `blur`.

https://github.com/github/auto-complete-element/blob/466c1f68473a0cee560acbf4971d84111e34d663/src/autocomplete.js#L106-L109

## Test
1. Type something
2. Click and drag an option outside the results list
3. Try to close the popup without selecting any option from the results list

## Possible solution
Change `mousedown`/`mouseup` for `mouseenter`/`mouseleave`?

### PR DESCRIPTION
**Pull request by muan**
Fixes #18.

| Before | After |
| -- | -- |
|  |  |

The result list is closed when:

1. Input value is cleared
1. Input is blurred and `mouseDown === false` ⚠️ 
1. Pressing <kbd>Escape</kbd> while focusing on input
1. An option is selected

### Problem

We relied on `mouseup` event to happen on `results` in order to reset `mouseDown` flag, which is what `input.onblur` checks in order to not close results prematurely (before `click`). 

When user drags outside of `results` (likely to avoid click/committing to a wrong option), `mouseup` happens outside of the element – not captured. `mouseDown` stays `true`, and blurring to close (2.) no longer works.

### Solution

Auto reset `mouseDown` flag on timeout instead of relying on `mouseup`.

### CODE REVIEW

File: src/autocomplete.js [hunk 1]
```diff
@@ -101,7 +101,7 @@ export default class Autocomplete {
 
   onResultsMouseDown() {
     this.mouseDown = true
-    this.results.addEventListener('mouseup', () => (this.mouseDown = false), {once: true})
+    setTimeout(() => (this.mouseDown = false), 100)
```
Comment (dgraham) [inline src/autocomplete.js]: Is the 100 ms value important or can it be 0 to indicate it needs to happen sometime soon in the future? Right now, the 100 value is a magic number that we don't know if we should increase or decrease in the future.

Comment (dgraham) [inline src/autocomplete.js]: Because we can't guarantee the `mouseup` event will happen on the result list, another fix would be to listen on document. That relies on any intermediate `mouseup` handlers not stopping event propagation up the tree, though.
